name: flutter_memory
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 2.1.1+27
version: 2.1.4+29

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
#dependency_overrides:
#  intl: ^0.17.0-nullsafety.2
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.

  #  flutter_image_compress: 0.7.0
  #  local_auth_device_credentials: 0.6.3+10
  cloud_firestore: 1.0.4
  connectivity: 3.0.3
  firebase_auth: 1.1.2
  firebase_crashlytics: 0.1.4+1
  firebase_storage: 8.0.5
  floating_action_bubble: 1.0.9
  flutter_archive: ^2.0.1
  flutter_calendar_carousel: 1.5.3
  flutter_holo_date_picker: 0.2.1
  flutter_image_compress: 1.0.0
  flutter_inappwebview: 5.3.1+1
  flutter_launcher_icons: 0.9.0
  flutter_platform_widgets: 1.1.0
  flutter_screen_lock: 1.2.4
  fluttertoast: 7.1.1
  geolocator: ^5.1.3
  http: 0.13.2
  image_downloader: 0.20.0
  image_picker: 0.7.4
  international_phone_input: 1.0.4
  intl: 0.17.0
  intl_phone_field: ^1.4.2
  mailer: 3.2.1
  package_info: 0.4.3+2
  passcode_screen: 1.2.0
  path_provider: 2.0.1
  pdf: 3.0.1
  permission_handler: 6.1.1
  photo_view: ^0.10.3
  printing: 5.0.4
  provider: ^4.0.4
  share: 0.6.5+4
  shared_preferences: 2.0.5
  transparent_image: ^0.1.0
  url_launcher: 6.0.3
  version: ^1.0.0
  excel:
  syncfusion_flutter_xlsio: 19.1.55-beta

#  downloads_path_provider: 0.1.0
# The following section is specific to Flutter.
flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lang/
    - images/
    - assets/manual.html
    - assets/image001.jpg
    - assets/image002.jpg
    - assets/image003.jpg
    - assets/image004.jpg
    - assets/image005.jpg
    - assets/image006.jpg



  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf

module:
  androidX: true
  # To add assets to your application, add an assets section, like this:
  #  assets:
  #  - images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages